sonar.projectKey=thang2k6adu_JT291-flutter-mobile
sonar.organization=thang2k6adu
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

# Thư mục chứa code chính
sonar.sources=lib

# Nếu có test
sonar.tests=test
sonar.exclusions=**/*.g.dart

# Ngôn ngữ chính
sonar.language=dart