// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSkVfJxF4Ik9Pa7I5s_NUCFm8NvaCZzY',
    appId: '1:790970286951:web:b1561a6ac544b96f3425c2',
    messagingSenderId: '790970286951',
    projectId: 'my-first-mobile-app-f4a85',
    authDomain: 'my-first-mobile-app-f4a85.firebaseapp.com',
    storageBucket: 'my-first-mobile-app-f4a85.firebasestorage.app',
    measurementId: 'G-9H152C3KLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcQvRTMKhI56JZbir1bly9boVv5TP319s',
    appId: '1:790970286951:android:b6787e02fb632aa13425c2',
    messagingSenderId: '790970286951',
    projectId: 'my-first-mobile-app-f4a85',
    storageBucket: 'my-first-mobile-app-f4a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-pV91719s8FMCVmG3_w_lraw0j5AH38',
    appId: '1:790970286951:ios:e3bb7da1348288743425c2',
    messagingSenderId: '790970286951',
    projectId: 'my-first-mobile-app-f4a85',
    storageBucket: 'my-first-mobile-app-f4a85.firebasestorage.app',
    iosBundleId: 'com.example.flutterBoilerplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-pV91719s8FMCVmG3_w_lraw0j5AH38',
    appId: '1:790970286951:ios:e3bb7da1348288743425c2',
    messagingSenderId: '790970286951',
    projectId: 'my-first-mobile-app-f4a85',
    storageBucket: 'my-first-mobile-app-f4a85.firebasestorage.app',
    iosBundleId: 'com.example.flutterBoilerplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJSkVfJxF4Ik9Pa7I5s_NUCFm8NvaCZzY',
    appId: '1:790970286951:web:1626e1eff6fe1c2d3425c2',
    messagingSenderId: '790970286951',
    projectId: 'my-first-mobile-app-f4a85',
    authDomain: 'my-first-mobile-app-f4a85.firebaseapp.com',
    storageBucket: 'my-first-mobile-app-f4a85.firebasestorage.app',
    measurementId: 'G-HS7CPM5HZ7',
  );
}
